### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by ghelfer** [huangenyan/MathSwift#1]
Firstly, great work! 
Well, my project is built in Swift 3, I was trying to use your library but while xcode converted it in Swift 3 a lot of issues appeared. Could you please help me with this?

Type 'Matrix' does not conform to protocol 'Sequence'
Value of type 'Range' has no member 'map'

Thanks

**Comment by huangenyan** [comment]
OK, I'm working on it.
I'll commit a new version as soon as possible.

Thanks!

**Comment by huangenyan** [comment]
Version 2.0 is just released for being compatible with Swift 3. Just have a try!

**Comment by huangenyan** [comment]
The new version should work well with Swift 3. The issue is closed.

**Comment by ghelfer** [comment]
I am with problem to access it...

2016-10-26 5:24 GMT-02:00 Evan E. Huang notifications@github.com:

**Comment by ghelfer** [comment]
great!
Thanks

2016-10-26 11:47 GMT-02:00 Gilson Augusto Helfer ghelfer@gmail.com:
