### ISSUE TITLE
svd issue

### ISSUE THREAD

**Issue by ghelfer** [huangenyan/MathSwift#5]
I compare your SVD function with  [wannyk](https://gist.github.com/wannyk/04c1f48161780322c0bb) and the results are different.
Mathlab shows same wannyk solution.
For use wannyk svd you need to 'flat' the matrix as an array of columns and inform its size (m x n).
Thanks,

**Comment by huangenyan** [comment]
I have fixed the error. It is due to a mistake when calculating transpose matrix for non-square matrix.
The new version 2.3 should now produce the correct answer.
