### ISSUE TITLE
Simultaneous accesses to var 'N'

### ISSUE THREAD

**Issue by gsabran** [huangenyan/MathSwift#8]
I'm getting the error:
```
Simultaneous accesses to var 'N', but modification requires exclusive access; consider copying to a local variable
```
 for
```swift
dgetrf_(&N, &N, &inMatrix, &N, &pivots, &error)
```

in Xcode 9

**Comment by huangenyan** [comment]
I think the reason is that Xcode 9 uses Swift 4 by default and currently MathSwift is in Swift 3.

**Comment by huangenyan** [comment]
I don't know if there is some "compatibility mode" in Xcode 9 to compile the framework in Swift 3. Generally I'd like to upgrade this framework to Swift 4 after the final release of Xcode 9.

I'll try to prepare a beta version to support Swift 4 if I have time recently.

**Comment by gsabran** [comment]
That'd be nice to help developers prepare in advance for iOS11 release. Thanks!

**Comment by huangenyan** [comment]
MathSwift 3 is finally released with Swift 4 support. Sorry for the late update!

**Comment by gsabran** [comment]
Excellent, great!
